.\"   SPDX-License-Identifier: BSD-3-Clause
.\"   Copyright(c) 2007-2026 Intel Corporation
.\" 
.\"   These contents may have been developed with support from one or more
.\"   Intel-operated generative artificial intelligence solutions.
.\"
.TH qat_init.sh 8 "30 Oct 2019"  qat_init.sh man page
.SH NAME
qat_init.sh \- QAT resource initializer
.SY qat_init.sh
.SH SYNOPSIS
.B qat_init.sh
.SH DESCRIPTION
.B qat_init.sh
initializes the Intel\(co Quick Assist Technology (Intel\(co QAT) devices in preparation for use
by the user space library (qatlib).
.PP
When run on a host system with physical function (PF) QAT devices visible and bound to the QAT device driver,
the qat_init.sh script will enable sriov on each of the PF devices. This enables the virtual function (VF) devices.
.PP
For each of the QAT VF devices, the qat_init.sh binds the device to the vfio-pci device driver, making it available
for applications using the qatlib user space library.
.SH ENVIRONMENT VARIABLES
\fBLKCF_LIST\fR
if set, gives a list of VF devices that should be used for accelerating operations from the Linux crypto framework instead of being available for user space applications.
.PP
Example:
.EX
LKCF_LIST="0000:3d:01.0 0000:3f:01.0 0000:da:01.0"
.EE
.SH SEE ALSO
qatmgr(8)
.SH AUTHOR
Conor McLoughlin <conor.mcloughlin@intel.com>
